### ISSUE TITLE
recording-importer does not follow redirects

### ISSUE THREAD

**Issue by Kunsi** [voc/voctopublish#105]
This is important to do for something like dropbox, where you get a "direct download" link, but you get redirected twice to the actual file somewhere in the CDN

**Comment by derpeter** [comment]
I did not look into this for many years. Last time i cheked dropbox & friends dont use simple redirects. Without a browser and JS you don't get the URL. For simple redirects we could use wget/curl but this will only help for "normal" servers not share hosters.

**Comment by Kunsi** [comment]
Atleast for dropbox using `wget` worked. This is what i want. No need for fancy javascript handling and whatnot.

**Comment by Kunsi** [comment]
Now available in `main`.
