### ISSUE TITLE
Handle not set, optional properties as false

### ISSUE THREAD

**Issue by derpeter** [voc/voctopublish#53]
Instead of requering e.g. Publishing.Mastodon.Enable to be set even if we dont want it we should handle this as false. This would reduce the amount of properties needed to be set.
This should be changed for:

- Twitter
- Mastodon
- Voctoweb
- Youtube

**Comment by derchrisuk** [comment]
Yes, I would only explicitly enable them if required, otherwise leave them disabled.

**Comment by Kunsi** [comment]
voctopublish now (well, since a couple of months now) supports defaults for tracker properties which can be set via the configuration file.
