### ISSUE TITLE
More tags for voctoweb, part 1

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctopublish#61]
As of now we only put conference acronym, local frab id and track into the voctoweb tags attribute list.
We should discuss how we get more tags for in individual talk into voctoweb, part 1:
* [x] add year as tag https://github.com/voc/voctoweb/issues/14
* [x] add new property for static conference tags named `Publishing.Tags`?
* [x] merge YouTube tags from tracker properties `Publishing.Tags`  and `Publishing.YouTube.Tags`
* [x] use static conference tags from tracker property `Publishing.Tags` also for Voctoweb
  * maybe recycle some? code from https://github.com/voc/voctopublish/blob/a2f798bbcd621d3bd1ab1ee4047ac3f0d59e21f4/voctopublish/api_client/youtube_client.py#L246-L286

(extracted from #57)

**Comment by derpeter** [comment]
Instead of using youtube tags we should have a global tag properties. If youtube needs extra tags we can concatenate that.
Adding the year is not problem.
There is not much code to recycle also the youtube code is not very nice. 
Why are this checkboxes anyway if this is discussion?

**Comment by saerdnaer** [comment]
The checkboxes can be ticked off, when the item is implemented.

**Comment by derpeter** [comment]
I know what a checkbox is but they only make sense after a discussion not at the start of one.

**Comment by derpeter** [comment]
Thinks discussed here are now implemented
