### ISSUE TITLE
Voctoweb link is missing when we rerelase to youtube 

### ISSUE THREAD

**Issue by bjoern-r** [voc/voctopublish#66]
The link to voctoweb is only added if publishing to voctoweb is enabled, however if we do a rerelase to youtube only, then the voctoweb url is present in the properties but voctoweb is disabled. In my opinion the release process should add the voctoweb url to the youtube description if the URL is available regardless of the Voctoweb.Enable property.

Place in the code:
https://github.com/voc/voctopublish/blob/38d35ced106f35d44ed0c95f191d5f26c51239cc/voctopublish/api_client/youtube_client.py#L139

**Comment by derpeter** [comment]
fixed by https://github.com/voc/voctopublish/commit/06cc57de22db1a10891034efbb4266495998b945
