### ISSUE TITLE
adding youtube video to playlist failed on chaostalk project

### ISSUE THREAD

**Issue by derpeter** [voc/voctopublish#70]
eb 20 23:24:21 releasing.c3voc.de sh[809]:     'Adding video to playlist failed with error-code %u: %s' % (r.status_code, r.text))
Feb 20 23:24:21 releasing.c3voc.de sh[809]: api_client.youtube_client.YouTubeException: Adding video to playlist failed with error-code 403: {
Feb 20 23:24:21 releasing.c3voc.de sh[809]:  "error": {
Feb 20 23:24:21 releasing.c3voc.de sh[809]:   "errors": [
Feb 20 23:24:21 releasing.c3voc.de sh[809]:    {
Feb 20 23:24:21 releasing.c3voc.de sh[809]:     "domain": "youtube.playlistItem",
Feb 20 23:24:21 releasing.c3voc.de sh[809]:     "reason": "playlistItemsNotAccessible",
Feb 20 23:24:21 releasing.c3voc.de sh[809]:     "message": "Forbidden"
Feb 20 23:24:21 releasing.c3voc.de sh[809]:    }
Feb 20 23:24:21 releasing.c3voc.de sh[809]:   ],
Feb 20 23:24:21 releasing.c3voc.de sh[809]:   "code": 403,
Feb 20 23:24:21 releasing.c3voc.de sh[809]:   "message": "Forbidden"
Feb 20 23:24:21 releasing.c3voc.de sh[809]:  }
Feb 20 23:24:21 releasing.c3voc.de sh[809]: }

**Comment by saerdnaer** [comment]
Welche Playlist URL hattest du da angegeben? Hat der YouTube Account dazu Schreibzugriff?

**Comment by derpeter** [comment]
Kann ich nicht mehr sagen. Würde es erst mal closen und wir schauen ob es in noch mal passiert.
